model_list:
- litellm_params:
    api_key: os.environ/GOOGLE_API_KEY
    model: gemini/gemini-1.5-pro-latest
  model_name: gpt-4o
- litellm_params:
    api_key: os.environ/SAMBANOVA_API_KEY
    model: sambanova/Meta-Llama-3.1-405B-Instruct
  model_name: gpt-3.5-turbo
- litellm_params:
    api_key: os.environ/SAMBANOVA_API_KEY
    model: sambanova/Meta-Llama-3.1-405B-Instruct
  model_name: gpt-3.5-turbo-0613
  
