name: Sync to Hugging Face Space

on:
  push:
    branches:
      - main
      - rogermt-patch-1
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Generate requirements.txt
        run: |
          poetry export -f requirements.txt --output requirements.txt --without-hashes

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add requirements.txt
          git commit -m "Update requirements.txt" || exit 0
          git push

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          BRANCH_NAME: ${{ github.ref_name }}
        run: |
          git push --force https://rogermt:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/rogermt/Arc-Finetuning $BRANCH_NAME
